import dynamic from "next/dynamic";
import { Inter } from "next/font/google";
import { getTranslations, unstable_setRequestLocale } from "next-intl/server";
import { ReactNode, Suspense } from "react";
import Navigation from "components/Navigation";
import TopHeader from "components/TopHeader";
import Footer from "components/Footer";
import { locales } from "../../config";
import type { Metadata } from "next";
import LoadingSkeleton from "components/LoadingSkeleton";
import StyledComponentsRegistry from "lib/antd.registry";
import Header from "components/Header";
const ReduxProvider = dynamic(() => import("./../../store/redux-provider"), {
  ssr: false,
});

const inter = Inter({ subsets: ["latin"] });

type Props = {
  children: ReactNode;
  params: { locale: string };
};

// export function generateStaticParams() {
//   return locales.map((locale) => ({locale}));
// }
/* SEO =========================== */
// export async function generateMetadata({
//   params: {locale}
// }: Omit<Props, 'children'>) {
//   const t = await getTranslations({locale, namespace: 'SEO'});

//   return {
//     title: t('title')
//   };
// }

export const metadata: Metadata = {
  title: "phi long tai thien",
  description: "Generated by create next app",
};
/* SEO =========================== */

export default async function LocaleLayout({
  children,
  params: { locale },
}: Props) {
  // Enable static rendering
  unstable_setRequestLocale(locale);

  return (
    <html lang={locale}>
      <body className={inter.className}>
        <div className="app-wrapper">
          <StyledComponentsRegistry>
            <ReduxProvider>
              <TopHeader></TopHeader>
              <Header />
              <Navigation />
              <Suspense fallback={<LoadingSkeleton />}>{children}</Suspense>
              <Footer></Footer>
            </ReduxProvider>
          </StyledComponentsRegistry>
        </div>
      </body>
    </html>
  );
}
