import clsx from "clsx";
import { Inter } from "next/font/google";
import { getTranslations, unstable_setRequestLocale } from "next-intl/server";
import { ReactNode, Suspense } from "react";
import Navigation from "components/Navigation";
import { locales } from "../../config";
import type { Metadata } from "next";
import LoadingSkeleton from "components/LoadingSkeleton";
import StyledComponentsRegistry from "lib/antd.registry";

const inter = Inter({ subsets: ["latin"] });

type Props = {
  children: ReactNode;
  params: { locale: string };
};

// export function generateStaticParams() {
//   return locales.map((locale) => ({locale}));
// }
/* SEO =========================== */
// export async function generateMetadata({
//   params: {locale}
// }: Omit<Props, 'children'>) {
//   const t = await getTranslations({locale, namespace: 'SEO'});

//   return {
//     title: t('title')
//   };
// }

export const metadata: Metadata = {
  title: "phi long tai thien",
  description: "Generated by create next app",
};
/* SEO =========================== */

export default async function LocaleLayout({
  children,
  params: { locale },
}: Props) {
  // Enable static rendering
  unstable_setRequestLocale(locale);

  return (
    <html className="h-full" lang={locale}>
      <body className={clsx(inter.className, "flex h-full flex-col")}>
        <StyledComponentsRegistry>
          <Navigation />
          <Suspense fallback={<LoadingSkeleton />}>{children}</Suspense>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
